### ISSUE TITLE
Mod ignores server defined fly speeds.

### ISSUE THREAD

**Issue by storm345** [BlueAnanas/ZebrasToggleSneak#3]
If a server, eg. MineTheftAuto, slows down the fly speed from 0.05 to 0.02 the mod ignores this in the current released stable version. Latest code on the repo looks to likely fix this horizontally, but will need testing, however it is still broken vertically.

**Comment by BlueAnanas** [comment]
Could you please specify what you used as **_the current released stable version_** There are currently 4 stable releases (for MC 1.8, 1.8.8, 1.8.9, and 1.9) with compiled binaries found on [releases](https://github.com/BlueAnanas/ZebrasToggleSneak/releases)

> however it is still broken vertically

could you be more specific?

Are you aware of the fact that this mod, in contrast to other, does not change the clients player main movement class? It only influences the vertical speed **in creative mode AND on boost activation**. If these two conditions are not **both** met, vertical speed is controlled by unchanged vanilla Minecraft code.

**Comment by BlueAnanas** [comment]
I think we cleared up this to be an non issue. ;-)
